2020-06-24_17-46-16: DF Exception: Sub: R1137E, Sess: 0, BdbQuit, , file: <ipython-input-4-1bb1bac423e2>, line no: 278
2020-06-24_17-49-07: DF Exception: Sub: R1137E, Sess: 0, IndexError, index 24 is out of bounds for axis 0 with size 24, file: <ipython-input-5-b3ce9569776d>, line no: 281
2020-06-24_18-03-28: DF Exception: Sub: R1137E, Sess: 0, BdbQuit, , file: <ipython-input-7-16c49a5d9bde>, line no: 281
2020-06-24_19-08-54: DF Exception: Sub: R1308T, Sess: 0, BdbQuit, , file: <ipython-input-12-218aa26ae4a2>, line no: 279
2020-06-24_19-14-49: DF Exception: Sub: R1308T, Sess: 0, BdbQuit, , file: <ipython-input-13-b735943276fa>, line no: 280
2020-06-24_19-19-50: DF Exception: Sub: R1308T, Sess: 0, BdbQuit, , file: <ipython-input-14-8ad378c07494>, line no: 144
2020-06-24_19-38-42: DF Exception: Sub: R1045E, Sess: 0, BdbQuit, , file: <ipython-input-16-0e0013763390>, line no: 143
2020-06-24_19-44-09: DF Exception: Sub: R1045E, Sess: 0, BdbQuit, , file: <ipython-input-17-68efd916337e>, line no: 147
2020-06-24_19-49-42: DF Exception: Sub: R1045E, Sess: 0, BdbQuit, , file: <ipython-input-18-121a0ea1f6c1>, line no: 148
2020-07-02_00-41-20: DF Exception: Sub: R1027J, Sess: 0, BdbQuit, , file: <ipython-input-4-214e3270ccac>, line no: 171
2020-07-02_00-41-30: DF Exception: Sub: R1033D, Sess: 0, BdbQuit, , file: <ipython-input-4-214e3270ccac>, line no: 171
2020-07-02_00-41-58: DF Exception: Sub: R1034D, Sess: 0, BdbQuit, , file: <ipython-input-4-214e3270ccac>, line no: 171
2020-07-02_00-42-00: DF Exception: Sub: R1034D, Sess: 1, BdbQuit, , file: <ipython-input-4-214e3270ccac>, line no: 171
2020-07-02_00-42-02: DF Exception: Sub: R1034D, Sess: 2, BdbQuit, , file: <ipython-input-4-214e3270ccac>, line no: 171
2020-07-02_00-43-31: DF Exception: Sub: R1033D, Sess: 0, BdbQuit, , file: <ipython-input-6-214e3270ccac>, line no: 169
2020-07-02_00-50-06: DF Exception: Sub: R1033D, Sess: 0, BdbQuit, , file: <ipython-input-7-e7879d26cc33>, line no: 279
2020-07-04_13-23-48: DF Exception: Sub: R1045E, Sess: 0, TypeError, '(slice(0, 263, None), slice(None, None, None))' is an invalid key, file: <ipython-input-3-6a0c666dcb42>, line no: 125
2020-07-04_13-28-46: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_42, file: , line no: XXX
2020-07-04_13-29-19: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_43, file: , line no: XXX
2020-07-04_13-30-04: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_50, file: , line no: XXX
2020-07-04_13-30-34: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_58, file: , line no: XXX
2020-07-04_13-30-51: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_59, file: , line no: XXX
2020-07-04_13-31-28: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_78, file: , line no: XXX
2020-07-04_13-32-24: DF Exception: Sub: R1045E, Sess: 0, Manual error, Encoded word key and ripple_array dont match for R1045E0_97, file: , line no: XXX
2020-07-20_17-29-13: DF Exception: Sub: R1010J, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-30-5a63870eb20b>, line no: 277
2020-07-20_17-29-28: DF Exception: Sub: R1112M, Sess: 2, ValueError, Events must correspond to one subject only, file: <ipython-input-30-5a63870eb20b>, line no: 137
2020-07-20_20-08-02: DF Exception: Sub: R1106M, Sess: 0, IndexError, index 20 is out of bounds for axis 0 with size 20, file: <ipython-input-5-5a63870eb20b>, line no: 89
2020-07-20_20-08-11: DF Exception: Sub: R1106M, Sess: 1, BdbQuit, , file: <ipython-input-5-5a63870eb20b>, line no: 89
2020-07-20_20-09-31: DF Exception: Sub: R1106M, Sess: 0, IndexError, index 20 is out of bounds for axis 0 with size 20, file: <ipython-input-6-5a63870eb20b>, line no: 89
2020-07-20_20-10-07: DF Exception: Sub: R1106M, Sess: 1, BdbQuit, , file: <ipython-input-6-5a63870eb20b>, line no: 89
2020-07-20_20-10-39: DF Exception: Sub: R1106M, Sess: 0, BdbQuit, , file: <ipython-input-7-5a63870eb20b>, line no: 89
2020-07-20_20-10-44: DF Exception: Sub: R1106M, Sess: 1, BdbQuit, , file: <ipython-input-7-5a63870eb20b>, line no: 89
2020-07-20_20-12-07: DF Exception: Sub: R1106M, Sess: 1, BdbQuit, , file: <ipython-input-8-5a63870eb20b>, line no: 89
2020-07-21_14-24-56: DF Exception: Sub: R1106M, Sess: 0, BdbQuit, , file: <ipython-input-5-82cfc619b828>, line no: 93
2020-07-21_14-24-58: DF Exception: Sub: R1106M, Sess: 1, BdbQuit, , file: <ipython-input-5-82cfc619b828>, line no: 93
2020-07-23_01-45-38: DF Exception: Sub: R1106M, Sess: 0, BdbQuit, , file: <ipython-input-4-d7f404b7f88a>, line no: 86
2020-07-23_01-45-40: DF Exception: Sub: R1106M, Sess: 1, BdbQuit, , file: <ipython-input-4-d7f404b7f88a>, line no: 86
2020-07-28_13-38-04: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-5-8814f0b8531d>, line no: 117
2020-07-28_13-38-04: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'list_recall' is not defined, file: <ipython-input-5-8814f0b8531d>, line no: 117
2020-07-28_13-38-08: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'list_recall' is not defined, file: <ipython-input-6-4f3dd0527103>, line no: 119
2020-07-28_13-38-08: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'list_recall' is not defined, file: <ipython-input-6-4f3dd0527103>, line no: 119
2020-07-28_14-11-07: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'numpy.int64' object is not iterable, file: <ipython-input-4-01bdf2e3146e>, line no: 120
2020-07-28_14-11-07: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'numpy.int64' object is not iterable, file: <ipython-input-4-01bdf2e3146e>, line no: 120
2020-07-28_14-11-53: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'PCA' is not defined, file: <ipython-input-8-199ee20c96b0>, line no: 127
2020-07-28_14-11-53: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'PCA' is not defined, file: <ipython-input-8-199ee20c96b0>, line no: 127
2020-07-28_14-12-36: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'itertools' is not defined, file: <ipython-input-9-9e3bbca07a0e>, line no: 135
2020-07-28_14-12-36: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'itertools' is not defined, file: <ipython-input-9-9e3bbca07a0e>, line no: 135
2020-07-28_14-27-32: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'itertools' is not defined, file: <ipython-input-10-9e3bbca07a0e>, line no: 135
2020-07-28_14-27-32: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'itertools' is not defined, file: <ipython-input-10-9e3bbca07a0e>, line no: 135
2020-07-28_14-52-41: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-3-90df0a06b4ce>, line no: 142
2020-07-28_14-52-43: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-3-90df0a06b4ce>, line no: 142
2020-07-28_14-55-57: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-4-e41b83f1e559>, line no: 142
2020-07-28_14-55-59: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-4-e41b83f1e559>, line no: 142
2020-07-28_15-04-11: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-10-bf6dfe4de7e4>, line no: 150
2020-07-28_15-04-13: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-10-bf6dfe4de7e4>, line no: 150
2020-07-28_15-06-01: DF Exception: Sub: R1112M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-12-ea412786504f>, line no: 356
2020-07-28_15-06-04: DF Exception: Sub: R1112M, Sess: 2, ValueError, Item wrong length 1 instead of 0., file: <ipython-input-12-ea412786504f>, line no: 149
2020-07-28_17-17-39: DF Exception: Sub: R1112M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-14-19a225933412>, line no: 358
2020-07-28_17-42-49: DF Exception: Sub: R1112M, Sess: 2, BdbQuit, , file: <ipython-input-14-19a225933412>, line no: 149
2020-07-28_17-53-52: DF Exception: Sub: R1112M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-15-9c99128ecae8>, line no: 359
2020-07-28_17-54-13: DF Exception: Sub: R1112M, Sess: 1, BdbQuit, , file: <ipython-input-15-9c99128ecae8>, line no: 357
2020-07-28_17-58-59: DF Exception: Sub: R1112M, Sess: 0, BdbQuit, , file: <ipython-input-18-9c99128ecae8>, line no: 357
2020-07-28_17-59-06: DF Exception: Sub: R1112M, Sess: 1, BdbQuit, , file: <ipython-input-18-9c99128ecae8>, line no: 357
2020-07-28_17-59-22: DF Exception: Sub: R1112M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-19-796a37f18be1>, line no: 358
2020-07-28_17-59-55: DF Exception: Sub: R1002P, Sess: 0, KeyError, 'AXE', file: <ipython-input-22-796a37f18be1>, line no: 129
2020-07-28_17-59-55: DF Exception: Sub: R1002P, Sess: 1, KeyError, 'AXE', file: <ipython-input-22-796a37f18be1>, line no: 129
2020-07-28_17-59-55: DF Exception: Sub: R1003P, Sess: 0, KeyError, 'AXE', file: <ipython-input-22-796a37f18be1>, line no: 129
2020-07-28_17-59-56: DF Exception: Sub: R1003P, Sess: 1, KeyError, 'AXE', file: <ipython-input-22-796a37f18be1>, line no: 129
2020-07-28_17-59-56: DF Exception: Sub: R1006P, Sess: 0, KeyError, 'AXE', file: <ipython-input-22-796a37f18be1>, line no: 129
2020-07-28_17-59-56: DF Exception: Sub: R1006P, Sess: 1, KeyError, 'AXE', file: <ipython-input-22-796a37f18be1>, line no: 129
2020-07-28_18-10-31: DF Exception: Sub: R1002P, Sess: 0, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1002P, Sess: 1, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1003P, Sess: 0, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1003P, Sess: 1, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1006P, Sess: 0, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1006P, Sess: 1, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1010J, Sess: 0, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1010J, Sess: 1, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1112M, Sess: 0, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1112M, Sess: 1, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1112M, Sess: 2, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1163T, Sess: 0, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-10-31: DF Exception: Sub: R1163T, Sess: 1, NameError, name 'list_words' is not defined, file: <ipython-input-23-63d1bfaefe17>, line no: 116
2020-07-28_18-26-41: DF Exception: Sub: R1002P, Sess: 0, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-29-58: DF Exception: Sub: R1002P, Sess: 1, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-00: DF Exception: Sub: R1003P, Sess: 0, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-01: DF Exception: Sub: R1003P, Sess: 1, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-04: DF Exception: Sub: R1006P, Sess: 0, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-06: DF Exception: Sub: R1006P, Sess: 1, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-08: DF Exception: Sub: R1010J, Sess: 0, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-09: DF Exception: Sub: R1010J, Sess: 1, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-10: DF Exception: Sub: R1112M, Sess: 0, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-30-11: DF Exception: Sub: R1112M, Sess: 1, BdbQuit, , file: <ipython-input-24-9eef29579179>, line no: 118
2020-07-28_18-32-46: DF Exception: Sub: R1002P, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-25-699186467bb1>, line no: 120
2020-07-28_18-32-46: DF Exception: Sub: R1003P, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-25-699186467bb1>, line no: 120
2020-07-28_18-32-46: DF Exception: Sub: R1003P, Sess: 1, IndexError, boolean index did not match indexed array along dimension 0; dimension is 92 but corresponding boolean dimension is 96, file: <ipython-input-25-699186467bb1>, line no: 155
2020-07-28_18-32-46: DF Exception: Sub: R1006P, Sess: 0, IndexError, boolean index did not match indexed array along dimension 0; dimension is 75 but corresponding boolean dimension is 77, file: <ipython-input-25-699186467bb1>, line no: 155
2020-07-28_18-32-47: DF Exception: Sub: R1006P, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-25-699186467bb1>, line no: 120
2020-07-28_18-32-58: DF Exception: Sub: R1010J, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-25-699186467bb1>, line no: 120
2020-07-28_18-32-59: DF Exception: Sub: R1112M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-25-699186467bb1>, line no: 361
2020-07-28_19-08-31: DF Exception: Sub: R1002P, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-35-98ea2a39cc7b>, line no: 120
2020-07-28_19-08-31: DF Exception: Sub: R1003P, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-35-98ea2a39cc7b>, line no: 120
2020-07-28_19-08-44: DF Exception: Sub: R1003P, Sess: 1, IndexError, boolean index did not match indexed array along dimension 0; dimension is 92 but corresponding boolean dimension is 96, file: <ipython-input-35-98ea2a39cc7b>, line no: 389
2020-07-28_19-09-00: DF Exception: Sub: R1006P, Sess: 0, IndexError, boolean index did not match indexed array along dimension 0; dimension is 75 but corresponding boolean dimension is 77, file: <ipython-input-35-98ea2a39cc7b>, line no: 389
2020-07-28_19-09-01: DF Exception: Sub: R1006P, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-35-98ea2a39cc7b>, line no: 120
2020-07-28_19-09-12: DF Exception: Sub: R1010J, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-35-98ea2a39cc7b>, line no: 120
2020-07-28_19-09-13: DF Exception: Sub: R1112M, Sess: 0, ValueError, No column combination found. Please make sure that the specified columns exist in the dataframe, are numeric, and contains at least two unique values., file: <ipython-input-35-98ea2a39cc7b>, line no: 359
2020-07-29_01-27-21: DF Exception: Sub: R1236J, Sess: 0, BdbQuit, , file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-27-24: DF Exception: Sub: R1236J, Sess: 1, BdbQuit, , file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-27-25: DF Exception: Sub: R1236J, Sess: 2, BdbQuit, , file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-27-27: DF Exception: Sub: R1236J, Sess: 3, BdbQuit, , file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-27-27: DF Exception: Sub: R1425D, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-27-27: DF Exception: Sub: R1425D, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-27-29: DF Exception: Sub: R1425D, Sess: 2, BdbQuit, , file: <ipython-input-5-f3db84ded0eb>, line no: 151
2020-07-29_01-31-33: DF Exception: Sub: R1425D, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-6-09e167dd3d07>, line no: 123
2020-07-29_01-31-33: DF Exception: Sub: R1425D, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-6-09e167dd3d07>, line no: 123
2020-07-29_01-35-48: DF Exception: Sub: R1425D, Sess: 0, BdbQuit, , file: <ipython-input-8-24a0741a5768>, line no: 122
2020-07-29_01-35-51: DF Exception: Sub: R1425D, Sess: 1, BdbQuit, , file: <ipython-input-8-24a0741a5768>, line no: 122
2020-07-29_01-35-52: DF Exception: Sub: R1425D, Sess: 2, BdbQuit, , file: <ipython-input-8-24a0741a5768>, line no: 122
2020-07-29_01-36-02: DF Exception: Sub: R1425D, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-9-4c6f22c996f4>, line no: 123
2020-07-29_01-36-02: DF Exception: Sub: R1425D, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-9-4c6f22c996f4>, line no: 123
2020-07-29_01-39-37: DF Exception: Sub: R1425D, Sess: 1, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-13-8b7fd0f693f5>, line no: 123
2020-07-29_01-54-31: DF Exception: Sub: R1425D, Sess: 1, BdbQuit, , file: <ipython-input-14-ac094fd97f98>, line no: 122
2020-07-30_16-05-16: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-4-7e317b0dbcf8>, line no: 120
2020-07-30_16-05-18: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-4-7e317b0dbcf8>, line no: 120
2020-07-30_16-19-00: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-5-49905122149c>, line no: 121
2020-07-30_16-19-01: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-5-49905122149c>, line no: 121
2020-07-30_16-19-03: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-6-c327a16e56e5>, line no: 121
2020-07-30_16-19-03: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'int' object is not iterable, file: <ipython-input-6-c327a16e56e5>, line no: 121
2020-07-30_16-20-28: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-7-0928048ece69>, line no: 121
2020-07-30_16-20-30: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-7-0928048ece69>, line no: 121
2020-07-30_16-24-01: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-8-caa588dff528>, line no: 123
2020-07-30_16-24-02: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'int' object is not iterable, file: <ipython-input-8-caa588dff528>, line no: 123
2020-07-30_16-24-20: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-9-60809cd4891c>, line no: 123
2020-07-30_16-24-20: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'int' object is not iterable, file: <ipython-input-9-60809cd4891c>, line no: 123
2020-07-30_16-26-13: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-13-60809cd4891c>, line no: 123
2020-07-30_16-26-13: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'int' object is not iterable, file: <ipython-input-13-60809cd4891c>, line no: 123
2020-07-30_16-27-14: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-15-b7a33836a7d4>, line no: 122
2020-07-30_16-27-16: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-15-b7a33836a7d4>, line no: 122
2020-07-30_16-28-19: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-16-b7686a5af6c9>, line no: 123
2020-07-30_16-28-19: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'int' object is not iterable, file: <ipython-input-16-b7686a5af6c9>, line no: 123
2020-07-30_16-28-29: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-17-db8bdfa21204>, line no: 123
2020-07-30_16-28-29: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'int' object is not iterable, file: <ipython-input-17-db8bdfa21204>, line no: 123
2020-07-30_16-29-09: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-18-d81c22a2d964>, line no: 123
2020-07-30_16-29-11: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-18-d81c22a2d964>, line no: 123
2020-07-30_16-31-21: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-19-9c80ad9c9783>, line no: 124
2020-07-30_16-31-27: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-19-9c80ad9c9783>, line no: 124
2020-07-30_16-35-17: DF Exception: Sub: R1001P, Sess: 0, IndexError, index 3 is out of bounds for axis 0 with size 3, file: <ipython-input-24-1270b41a9c57>, line no: 124
2020-07-30_16-36-53: DF Exception: Sub: R1001P, Sess: 1, IndexError, index 3 is out of bounds for axis 0 with size 3, file: <ipython-input-24-1270b41a9c57>, line no: 124
2020-07-30_16-37-13: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-25-1270b41a9c57>, line no: 125
2020-07-30_16-37-15: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-25-1270b41a9c57>, line no: 125
2020-07-30_16-41-22: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-26-7f6e4df07fef>, line no: 124
2020-07-30_16-41-27: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-26-7f6e4df07fef>, line no: 124
2020-07-30_16-42-56: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-27-69b070c21f1e>, line no: 124
2020-07-30_16-42-57: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-27-69b070c21f1e>, line no: 124
2020-07-30_16-44-01: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-28-41bcb5ef2df0>, line no: 124
2020-07-30_16-44-03: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-28-41bcb5ef2df0>, line no: 124
2020-07-30_16-45-01: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'session_corrected_list_ops' is not defined, file: <ipython-input-29-b6d242b544d1>, line no: 124
2020-07-30_16-45-01: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'session_corrected_list_ops' is not defined, file: <ipython-input-29-b6d242b544d1>, line no: 124
2020-07-30_16-47-21: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-30-049f9ce7d053>, line no: 126
2020-07-30_16-47-47: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-30-049f9ce7d053>, line no: 218
2020-07-30_17-25-29: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-4-ae7ae33b51da>, line no: 125
2020-07-30_17-25-30: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-4-ae7ae33b51da>, line no: 125
2020-07-30_18-06-00: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'getOutputPositions' is not defined, file: <ipython-input-9-e5ddfeea9fbe>, line no: 115
2020-07-30_18-06-00: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'getOutputPositions' is not defined, file: <ipython-input-9-e5ddfeea9fbe>, line no: 115
2020-07-30_18-06-17: DF Exception: Sub: R1001P, Sess: 0, NameError, name 'getOutputPositions' is not defined, file: <ipython-input-10-e5ddfeea9fbe>, line no: 115
2020-07-30_18-06-17: DF Exception: Sub: R1001P, Sess: 1, NameError, name 'getOutputPositions' is not defined, file: <ipython-input-10-e5ddfeea9fbe>, line no: 115
2020-08-04_18-45-08: DF Exception: Sub: R1113T, Sess: 0, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1113T, Sess: 1, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1113T, Sess: 2, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1137E, Sess: 0, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1137E, Sess: 1, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1137E, Sess: 2, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1311T, Sess: 0, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1311T, Sess: 1, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-45-08: DF Exception: Sub: R1311T, Sess: 2, NameError, name 'temp_serialpos_lags' is not defined, file: <ipython-input-3-64a2ff545dbf>, line no: 157
2020-08-04_18-48-14: DF Exception: Sub: R1113T, Sess: 1, BdbQuit, , file: <ipython-input-4-382a2be2460a>, line no: 415
2020-08-13_11-20-09: DF Exception: Sub: R1308T, Sess: 0, BdbQuit, , file: <ipython-input-4-796ceabfed51>, line no: 265
2020-08-13_23-24-39: DF Exception: Sub: R1001P, Sess: 0, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-39: DF Exception: Sub: R1001P, Sess: 1, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-40: DF Exception: Sub: R1002P, Sess: 0, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-40: DF Exception: Sub: R1002P, Sess: 1, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-41: DF Exception: Sub: R1003P, Sess: 0, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-42: DF Exception: Sub: R1003P, Sess: 1, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-42: DF Exception: Sub: R1006P, Sess: 0, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-43: DF Exception: Sub: R1006P, Sess: 1, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-24-43: DF Exception: Sub: R1010J, Sess: 0, TypeError, 'float' object is not callable, file: <ipython-input-5-6674b07eddee>, line no: 112
2020-08-13_23-27-41: DF Exception: Sub: R1001P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-41: DF Exception: Sub: R1001P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-41: DF Exception: Sub: R1002P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-42: DF Exception: Sub: R1002P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-42: DF Exception: Sub: R1003P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-42: DF Exception: Sub: R1003P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-43: DF Exception: Sub: R1006P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-43: DF Exception: Sub: R1006P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-44: DF Exception: Sub: R1010J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-44: DF Exception: Sub: R1010J, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-44: DF Exception: Sub: R1018P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-45: DF Exception: Sub: R1020J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-46: DF Exception: Sub: R1022J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-47: DF Exception: Sub: R1023J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-47: DF Exception: Sub: R1026D, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-48: DF Exception: Sub: R1027J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-27-48: DF Exception: Sub: R1030J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-12-4bdb0d31815c>, line no: 115
2020-08-13_23-29-23: DF Exception: Sub: R1001P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-23: DF Exception: Sub: R1001P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-23: DF Exception: Sub: R1002P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-24: DF Exception: Sub: R1002P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-24: DF Exception: Sub: R1003P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-24: DF Exception: Sub: R1003P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-25: DF Exception: Sub: R1006P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-25: DF Exception: Sub: R1006P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-26: DF Exception: Sub: R1010J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-26: DF Exception: Sub: R1010J, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-26: DF Exception: Sub: R1018P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-26: DF Exception: Sub: R1020J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-27: DF Exception: Sub: R1022J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-27: DF Exception: Sub: R1023J, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-27: DF Exception: Sub: R1026D, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-13-4bdb0d31815c>, line no: 115
2020-08-13_23-29-44: DF Exception: Sub: R1001P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-29-45: DF Exception: Sub: R1001P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-29-45: DF Exception: Sub: R1002P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-29-45: DF Exception: Sub: R1002P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-29-46: DF Exception: Sub: R1003P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-29-46: DF Exception: Sub: R1003P, Sess: 1, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-29-46: DF Exception: Sub: R1006P, Sess: 0, IndexError, only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices, file: <ipython-input-14-4bdb0d31815c>, line no: 115
2020-08-13_23-34-37: DF Exception: Sub: R1001P, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-37: DF Exception: Sub: R1001P, Sess: 1, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-37: DF Exception: Sub: R1002P, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-38: DF Exception: Sub: R1002P, Sess: 1, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-38: DF Exception: Sub: R1003P, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-39: DF Exception: Sub: R1003P, Sess: 1, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-39: DF Exception: Sub: R1006P, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-39: DF Exception: Sub: R1006P, Sess: 1, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-40: DF Exception: Sub: R1010J, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-40: DF Exception: Sub: R1010J, Sess: 1, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-40: DF Exception: Sub: R1018P, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-41: DF Exception: Sub: R1020J, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-41: DF Exception: Sub: R1022J, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-41: DF Exception: Sub: R1023J, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-41: DF Exception: Sub: R1026D, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-42: DF Exception: Sub: R1027J, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-42: DF Exception: Sub: R1030J, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-42: DF Exception: Sub: R1031M, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-43: DF Exception: Sub: R1032D, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-43: DF Exception: Sub: R1033D, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-44: DF Exception: Sub: R1034D, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-44: DF Exception: Sub: R1034D, Sess: 1, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-44: DF Exception: Sub: R1034D, Sess: 2, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-44: DF Exception: Sub: R1035M, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-45: DF Exception: Sub: R1036M, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-45: DF Exception: Sub: R1039M, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-34-46: DF Exception: Sub: R1042M, Sess: 0, IndexError, string index out of range, file: <ipython-input-25-120fa512c8d0>, line no: 115
2020-08-13_23-35-07: DF Exception: Sub: R1001P, Sess: 0, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-07: DF Exception: Sub: R1001P, Sess: 1, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-07: DF Exception: Sub: R1002P, Sess: 0, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-08: DF Exception: Sub: R1002P, Sess: 1, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-08: DF Exception: Sub: R1003P, Sess: 0, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-08: DF Exception: Sub: R1003P, Sess: 1, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-09: DF Exception: Sub: R1006P, Sess: 0, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-09: DF Exception: Sub: R1006P, Sess: 1, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-10: DF Exception: Sub: R1010J, Sess: 0, IndexError, string index out of range, file: <ipython-input-26-120fa512c8d0>, line no: 115
2020-08-13_23-35-48: DF Exception: Sub: R1001P, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-48: DF Exception: Sub: R1001P, Sess: 1, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-49: DF Exception: Sub: R1002P, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-49: DF Exception: Sub: R1002P, Sess: 1, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-49: DF Exception: Sub: R1003P, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-50: DF Exception: Sub: R1003P, Sess: 1, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-50: DF Exception: Sub: R1006P, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-50: DF Exception: Sub: R1006P, Sess: 1, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-51: DF Exception: Sub: R1010J, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-51: DF Exception: Sub: R1010J, Sess: 1, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-51: DF Exception: Sub: R1018P, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-52: DF Exception: Sub: R1020J, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-52: DF Exception: Sub: R1022J, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-52: DF Exception: Sub: R1023J, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-35-53: DF Exception: Sub: R1026D, Sess: 0, IndexError, string index out of range, file: <ipython-input-27-120fa512c8d0>, line no: 115
2020-08-13_23-36-45: DF Exception: Sub: R1001P, Sess: 0, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-45: DF Exception: Sub: R1001P, Sess: 1, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-46: DF Exception: Sub: R1002P, Sess: 0, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-46: DF Exception: Sub: R1002P, Sess: 1, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-46: DF Exception: Sub: R1003P, Sess: 0, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-47: DF Exception: Sub: R1003P, Sess: 1, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-47: DF Exception: Sub: R1006P, Sess: 0, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-36-47: DF Exception: Sub: R1006P, Sess: 1, IndexError, string index out of range, file: <ipython-input-29-120fa512c8d0>, line no: 115
2020-08-13_23-38-19: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-38-22: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-38-23: DF Exception: Sub: R1002P, Sess: 0, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-39-18: DF Exception: Sub: R1002P, Sess: 1, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-39-21: DF Exception: Sub: R1003P, Sess: 0, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-39-25: DF Exception: Sub: R1003P, Sess: 1, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-39-26: DF Exception: Sub: R1006P, Sess: 0, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-13_23-39-27: DF Exception: Sub: R1006P, Sess: 1, BdbQuit, , file: <ipython-input-30-120fa512c8d0>, line no: 115
2020-08-14_09-16-22: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-5-120fa512c8d0>, line no: 119
2020-08-14_09-16-24: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-5-120fa512c8d0>, line no: 119
2020-08-14_09-16-27: DF Exception: Sub: R1002P, Sess: 0, BdbQuit, , file: <ipython-input-5-120fa512c8d0>, line no: 119
2020-08-14_09-16-29: DF Exception: Sub: R1002P, Sess: 1, BdbQuit, , file: <ipython-input-5-120fa512c8d0>, line no: 119
2020-08-14_09-20-26: DF Exception: Sub: R1001P, Sess: 0, BdbQuit, , file: <ipython-input-7-e40544a57b04>, line no: 119
2020-08-14_09-20-28: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-7-e40544a57b04>, line no: 119
2020-08-14_09-20-48: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-8-c8e7ed4d441b>, line no: 115
2020-08-14_09-20-48: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-8-c8e7ed4d441b>, line no: 115
2020-08-14_11-27-08: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-14-c8e7ed4d441b>, line no: 115
2020-08-14_11-27-08: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-14-c8e7ed4d441b>, line no: 115
2020-08-14_11-28-46: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-16-c8e7ed4d441b>, line no: 115
2020-08-14_11-28-47: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-16-c8e7ed4d441b>, line no: 115
2020-08-14_11-37-59: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-18-c8e7ed4d441b>, line no: 115
2020-08-14_11-38-00: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-18-c8e7ed4d441b>, line no: 115
2020-08-14_11-40-34: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-21-f2219ff04bdd>, line no: 116
2020-08-14_11-40-34: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-21-f2219ff04bdd>, line no: 116
2020-08-14_11-43-35: DF Exception: Sub: R1001P, Sess: 1, BdbQuit, , file: <ipython-input-25-f2219ff04bdd>, line no: 116
2020-08-14_11-43-37: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-25-f2219ff04bdd>, line no: 116
2020-08-14_11-43-38: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-25-f2219ff04bdd>, line no: 116
2020-08-14_11-44-25: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-26-f2219ff04bdd>, line no: 116
2020-08-14_11-44-26: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-26-f2219ff04bdd>, line no: 116
2020-08-14_11-48-21: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-31-f2219ff04bdd>, line no: 116
2020-08-14_11-48-21: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-31-f2219ff04bdd>, line no: 116
2020-08-14_11-53-00: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-35-f2219ff04bdd>, line no: 116
2020-08-14_11-53-01: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-35-f2219ff04bdd>, line no: 116
2020-08-14_12-01-20: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-38-f2219ff04bdd>, line no: 116
2020-08-14_12-01-20: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-38-f2219ff04bdd>, line no: 116
2020-08-14_12-25-10: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-43-f2219ff04bdd>, line no: 116
2020-08-14_12-25-11: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-43-f2219ff04bdd>, line no: 116
2020-08-14_12-27-59: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-45-f2219ff04bdd>, line no: 116
2020-08-14_12-27-59: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-45-f2219ff04bdd>, line no: 116
2020-08-14_12-31-18: DF Exception: Sub: R1367D, Sess: 0, BdbQuit, , file: <ipython-input-48-f2219ff04bdd>, line no: 116
2020-08-14_12-31-19: DF Exception: Sub: R1367D, Sess: 1, BdbQuit, , file: <ipython-input-48-f2219ff04bdd>, line no: 116
2020-08-14_12-31-22: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-48-f2219ff04bdd>, line no: 116
2020-08-14_12-31-24: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-48-f2219ff04bdd>, line no: 116
2020-08-14_12-31-25: DF Exception: Sub: R1467M, Sess: 0, BdbQuit, , file: <ipython-input-48-f2219ff04bdd>, line no: 116
2020-08-14_12-32-19: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-49-e1ff56d725aa>, line no: 116
2020-08-14_12-32-20: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-49-e1ff56d725aa>, line no: 116
2020-08-14_12-33-28: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-51-e1ff56d725aa>, line no: 116
2020-08-14_12-33-29: DF Exception: Sub: R1367D, Sess: 1, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-51-e1ff56d725aa>, line no: 116
2020-08-14_12-35-17: DF Exception: Sub: R1367D, Sess: 0, BdbQuit, , file: <ipython-input-52-e1ff56d725aa>, line no: 116
2020-08-14_12-35-18: DF Exception: Sub: R1367D, Sess: 1, BdbQuit, , file: <ipython-input-52-e1ff56d725aa>, line no: 116
2020-08-14_12-35-20: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-52-e1ff56d725aa>, line no: 116
2020-08-14_12-35-21: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-52-e1ff56d725aa>, line no: 116
2020-08-14_12-35-22: DF Exception: Sub: R1467M, Sess: 0, BdbQuit, , file: <ipython-input-52-e1ff56d725aa>, line no: 116
2020-08-14_12-35-40: DF Exception: Sub: R1367D, Sess: 0, ValueError, The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()., file: <ipython-input-53-e1ff56d725aa>, line no: 116
2020-08-14_12-37-13: DF Exception: Sub: R1367D, Sess: 1, BdbQuit, , file: <ipython-input-53-e1ff56d725aa>, line no: 116
2020-08-14_12-37-15: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-53-e1ff56d725aa>, line no: 116
2020-08-14_12-37-16: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-53-e1ff56d725aa>, line no: 116
2020-08-14_12-37-17: DF Exception: Sub: R1467M, Sess: 0, BdbQuit, , file: <ipython-input-53-e1ff56d725aa>, line no: 116
2020-08-14_12-37-54: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-54-e1ff56d725aa>, line no: 116
2020-08-14_12-37-54: DF Exception: Sub: R1463E, Sess: 1, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-54-e1ff56d725aa>, line no: 116
2020-08-14_12-42-49: DF Exception: Sub: R1367D, Sess: 0, TypeError, unsupported operand type(s) for &: 'str' and 'str', file: <ipython-input-62-e1ff56d725aa>, line no: 116
2020-08-14_12-42-50: DF Exception: Sub: R1367D, Sess: 1, TypeError, unsupported operand type(s) for &: 'str' and 'str', file: <ipython-input-62-e1ff56d725aa>, line no: 116
2020-08-14_12-42-50: DF Exception: Sub: R1463E, Sess: 0, TypeError, unsupported operand type(s) for &: 'str' and 'str', file: <ipython-input-62-e1ff56d725aa>, line no: 116
2020-08-14_12-42-50: DF Exception: Sub: R1463E, Sess: 1, TypeError, unsupported operand type(s) for &: 'str' and 'str', file: <ipython-input-62-e1ff56d725aa>, line no: 116
2020-08-14_12-42-51: DF Exception: Sub: R1467M, Sess: 0, TypeError, unsupported operand type(s) for &: 'str' and 'str', file: <ipython-input-62-e1ff56d725aa>, line no: 116
2020-08-14_12-43-24: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-63-e1ff56d725aa>, line no: 116
2020-08-14_12-43-24: DF Exception: Sub: R1463E, Sess: 1, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-63-e1ff56d725aa>, line no: 116
2020-08-14_12-44-46: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-67-e1ff56d725aa>, line no: 116
2020-08-14_12-44-46: DF Exception: Sub: R1463E, Sess: 1, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-67-e1ff56d725aa>, line no: 116
2020-08-14_13-06-28: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-69-3a123e84fe0b>, line no: 117
2020-08-14_13-06-28: DF Exception: Sub: R1463E, Sess: 1, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-69-3a123e84fe0b>, line no: 117
2020-08-14_13-06-28: DF Exception: Sub: R1467M, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-69-3a123e84fe0b>, line no: 122
2020-08-14_13-11-27: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-71-3a123e84fe0b>, line no: 117
2020-08-14_13-11-43: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-71-3a123e84fe0b>, line no: 117
2020-08-14_13-11-44: DF Exception: Sub: R1467M, Sess: 0, BdbQuit, , file: <ipython-input-71-3a123e84fe0b>, line no: 117
2020-08-14_13-14-49: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-73-3a123e84fe0b>, line no: 117
2020-08-14_13-14-50: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-73-3a123e84fe0b>, line no: 117
2020-08-14_13-14-51: DF Exception: Sub: R1467M, Sess: 0, BdbQuit, , file: <ipython-input-73-3a123e84fe0b>, line no: 117
2020-08-14_13-15-59: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-75-3a123e84fe0b>, line no: 117
2020-08-14_13-16-22: DF Exception: Sub: R1463E, Sess: 1, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-75-3a123e84fe0b>, line no: 117
2020-08-14_13-16-24: DF Exception: Sub: R1467M, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-75-3a123e84fe0b>, line no: 122
2020-08-14_13-36-54: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-76-6c5eb47ae297>, line no: 117
2020-08-14_13-36-55: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-76-6c5eb47ae297>, line no: 117
2020-08-14_13-39-16: DF Exception: Sub: R1463E, Sess: 0, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-81-6c5eb47ae297>, line no: 117
2020-08-14_13-39-17: DF Exception: Sub: R1463E, Sess: 1, IndexError, index 165 is out of bounds for axis 0 with size 165, file: <ipython-input-81-6c5eb47ae297>, line no: 117
2020-08-14_20-26-24: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-272-3918ab119e38>, line no: 117
2020-08-14_20-26-30: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-272-3918ab119e38>, line no: 117
2020-08-14_20-28-20: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-274-3918ab119e38>, line no: 117
2020-08-14_20-28-22: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-274-3918ab119e38>, line no: 117
2020-08-14_20-31-19: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-275-3918ab119e38>, line no: 117
2020-08-14_20-31-20: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-275-3918ab119e38>, line no: 117
2020-08-14_20-31-28: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-276-3918ab119e38>, line no: 117
2020-08-14_20-31-29: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-276-3918ab119e38>, line no: 117
2020-08-14_20-32-05: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-277-3918ab119e38>, line no: 117
2020-08-14_20-32-06: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-277-3918ab119e38>, line no: 117
2020-08-14_20-32-47: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-278-3918ab119e38>, line no: 117
2020-08-14_20-32-49: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-278-3918ab119e38>, line no: 117
2020-08-14_20-34-04: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-279-3918ab119e38>, line no: 117
2020-08-14_20-34-05: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-279-3918ab119e38>, line no: 117
2020-08-14_20-35-01: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-280-3918ab119e38>, line no: 117
2020-08-14_20-35-02: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-280-3918ab119e38>, line no: 117
2020-08-14_20-38-35: DF Exception: Sub: R1463E, Sess: 0, BdbQuit, , file: <ipython-input-283-3918ab119e38>, line no: 117
2020-08-14_20-38-37: DF Exception: Sub: R1463E, Sess: 1, BdbQuit, , file: <ipython-input-283-3918ab119e38>, line no: 117
