2020-10-08_22-58-19: DF Exception: Sub: R1093J, Sess: 0, NameError, name 'first_of_list_list' is not defined, file: <ipython-input-4-ee368a498316>, line no: 94
2020-10-08_23-02-16: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-5-ee368a498316>, line no: 94
2020-10-08_23-03-16: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-6-ee368a498316>, line no: 94
2020-10-08_23-15-41: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-7-ee368a498316>, line no: 94
2020-10-08_23-22-50: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-8-ee368a498316>, line no: 94
2020-10-08_23-23-51: DF Exception: Sub: R1093J, Sess: 0, TypeError, 'int' object is not iterable, file: <ipython-input-9-ee368a498316>, line no: 94
2020-10-08_23-25-55: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-10-ee368a498316>, line no: 94
2020-10-08_23-27-23: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-11-ee368a498316>, line no: 94
2020-10-08_23-30-44: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-12-ee368a498316>, line no: 94
2020-10-08_23-31-36: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-13-e7218482d997>, line no: 95
2020-10-08_23-32-05: DF Exception: Sub: R1093J, Sess: 0, BdbQuit, , file: <ipython-input-14-5508891d47f6>, line no: 95
2020-10-14_01-15-52: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-4-f90efb7f29c1>, line no: 164
2020-10-14_01-22-42: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-5-1072f0a205f0>, line no: 167
2020-10-14_01-27-23: DF Exception: Sub: R1169P, Sess: 0, NameError, name 'pcs' is not defined, file: <ipython-input-6-08bb62af33f6>, line no: 184
2020-10-14_01-30-29: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-10-0bc1e4b0e2e1>, line no: 160
2020-10-14_01-30-31: DF Exception: Sub: R1169P, Sess: 1, BdbQuit, , file: <ipython-input-10-0bc1e4b0e2e1>, line no: 160
2020-10-14_01-33-03: DF Exception: Sub: R1169P, Sess: 0, BdbQuit, , file: <ipython-input-14-0bc1e4b0e2e1>, line no: 181
2020-10-15_01-07-11: DF Exception: Sub: R1334T, Sess: 0, NameError, name 'recall_minimum' is not defined, file: <ipython-input-25-ed7d507a4bdd>, line no: 196
2020-10-15_01-07-11: DF Exception: Sub: R1368T, Sess: 0, NameError, name 'recall_minimum' is not defined, file: <ipython-input-25-ed7d507a4bdd>, line no: 196
2020-10-15_01-13-07: DF Exception: Sub: R1334T, Sess: 0, IndexError, boolean index did not match indexed array along dimension 0; dimension is 56 but corresponding boolean dimension is 80, file: <ipython-input-26-037d89b6f669>, line no: 452
2020-10-15_01-13-36: DF Exception: Sub: R1368T, Sess: 0, IndexError, boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 26, file: <ipython-input-26-037d89b6f669>, line no: 452
2020-10-15_02-08-39: DF Exception: Sub: R1334T, Sess: 0, IndexError, list index out of range, file: <ipython-input-4-57cbb0c1efc4>, line no: 172
2020-10-15_02-08-40: DF Exception: Sub: R1368T, Sess: 0, IndexError, list index out of range, file: <ipython-input-4-57cbb0c1efc4>, line no: 172
2020-10-16_18-26-57: DF Exception: Sub: R1334T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-4-5f750472c544>, line no: 135
2020-10-16_18-26-57: DF Exception: Sub: R1368T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-4-5f750472c544>, line no: 135
2020-10-16_18-27-09: DF Exception: Sub: R1334T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-5-5f750472c544>, line no: 135
2020-10-16_18-27-09: DF Exception: Sub: R1368T, Sess: 0, AttributeError, 'DataFrame' object has no attribute 'list_name', file: <ipython-input-5-5f750472c544>, line no: 135
2020-10-16_18-30-39: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-6-08229a458f5a>, line no: 141
2020-10-16_18-30-41: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-08229a458f5a>, line no: 141
2020-10-16_18-34-23: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-7-f7bc5d297c14>, line no: 148
2020-10-16_18-34-25: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-f7bc5d297c14>, line no: 141
2020-10-16_19-22-19: DF Exception: Sub: R1334T, Sess: 0, TypeError, unsupported operand type(s) for -: 'list' and 'int', file: <ipython-input-15-3ad3bb6602c3>, line no: 155
2020-10-16_19-22-19: DF Exception: Sub: R1368T, Sess: 0, TypeError, unsupported operand type(s) for -: 'list' and 'int', file: <ipython-input-15-3ad3bb6602c3>, line no: 155
2020-10-16_19-22-51: DF Exception: Sub: R1334T, Sess: 0, TypeError, cannot convert the series to <class 'int'>, file: <ipython-input-16-79d85da2b608>, line no: 175
2020-10-16_19-24-49: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-16-79d85da2b608>, line no: 173
2020-10-16_22-57-20: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-4-375a8a7ee21e>, line no: 202
2020-10-16_22-57-25: DF Exception: Sub: R1368T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-4-375a8a7ee21e>, line no: 202
2020-10-16_23-19-56: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-5-375a8a7ee21e>, line no: 202
2020-10-16_23-21-32: DF Exception: Sub: R1368T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-5-375a8a7ee21e>, line no: 202
2020-10-16_23-38-25: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-6-361e3f939ad9>, line no: 202
2020-10-16_23-39-54: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-6-361e3f939ad9>, line no: 202
2020-10-16_23-42-06: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-7-361e3f939ad9>, line no: 202
2020-10-16_23-44-36: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-7-361e3f939ad9>, line no: 202
2020-10-16_23-49-08: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-8-361e3f939ad9>, line no: 202
2020-10-16_23-49-08: DF Exception: Sub: R1368T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-8-361e3f939ad9>, line no: 202
2020-10-16_23-50-00: DF Exception: Sub: R1334T, Sess: 0, IndexError, index -1000 is out of bounds for axis 0 with size 12, file: <ipython-input-9-361e3f939ad9>, line no: 202
2020-10-16_23-53-03: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-9-361e3f939ad9>, line no: 202
2020-10-16_23-54-09: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-10-361e3f939ad9>, line no: 202
2020-10-16_23-54-10: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-10-361e3f939ad9>, line no: 202
2020-10-16_23-55-47: DF Exception: Sub: R1334T, Sess: 0, BdbQuit, , file: <ipython-input-11-361e3f939ad9>, line no: 226
2020-10-16_23-55-49: DF Exception: Sub: R1368T, Sess: 0, BdbQuit, , file: <ipython-input-11-361e3f939ad9>, line no: 226
